import React, {useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight, ArrowLeft, ArrowRight, Bookmark, BriefcaseBusiness, Building2, Check, CheckCheck, ChevronDown, ChevronRight, CircleHelp, Clock3, ExternalLink, FileText, GraduationCap, MapPin, Search, ShieldCheck, SlidersHorizontal, Sparkles, UserRound, X, Layers, CheckCircle2, Send, Copy, RotateCcw} from 'lucide-react';
import source from './jobs.json';
import './style.css';
import './xiaomi-logo.css';
import dewuLogo from './dewu-logo.png';

type Job = typeof source[number];
type Profile={text:string;education:string};
const read=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem('jobkoi-preview:'+key)||'null')??fallback;}catch{return fallback;}};
const shortTitle=(title:string)=>title.replace(/^【[^】]+】\s*/,'');
const companies=[...new Set(source.map(j=>j.company_name))];
const directions=[...new Set(source.map(j=>j.job_direction))];
const recruitmentTypes=[...new Set(source.map(j=>j.recruitment_type))];
const logoClass=(j:Job)=>`xhs-logo ${j.company_name==='美团'?'meituan-logo':j.company_name==='汽车之家'?'autohome-logo':j.company_name==='海康威视'?'hikvision-logo':j.company_name==='顺丰'?'sf-logo':''}`;
const CompanyLogo=({job,large=false}:{job:Job;large?:boolean})=>job.company_name==='得物'?<img className={`xhs-logo dewu-logo${large?' large':''}`} src={dewuLogo} alt="得物"/>:job.company_name==='小米科技'?<span className={`xhs-logo xiaomi-logo${large?' large':''}`} role="img" aria-label="小米科技"><span aria-hidden="true">mi</span></span>:job.company_name==='滴滴'?<span className={`xhs-logo didi-logo${large?' large':''}`} role="img" aria-label="滴滴"><span aria-hidden="true">滴滴</span></span>:job.company_name==='网易'?<span className={`xhs-logo netease-logo${large?' large':''}`} role="img" aria-label="网易"><span aria-hidden="true">网易</span></span>:<span className={`${logoClass(job)}${large?' large':''}`}>{job.company_name}</span>;
const publishedDate=(value:string|null)=>value?(value.length===10?value:new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value))):'未公布';
const companyCount=(name:string)=>source.filter(j=>j.company_name===name).length;
const cities=[...new Set(source.flatMap(j=>j.locations))];
const degrees=[...new Set(source.map(j=>j.education_requirement).filter((s):s is string=>!!s))];
function App(){
 const params=new URLSearchParams(location.search);
 const [query,setQuery]=useState(params.get('q')||'');const [city,setCity]=useState(params.get('city')||'');const [direction,setDirection]=useState(params.get('direction')||'');const [degree,setDegree]=useState(params.get('degree')||'');
 const [company,setCompany]=useState(params.get('company')||'');const [recruitmentType,setRecruitmentType]=useState(params.get('type')==='应届生'?'校招':params.get('type')||'');
 const [selectedId,setSelectedId]=useState(params.get('job')||source[0].source_job_id);
 const [view,setView]=useState<'all'|'saved'|'applied'>('all');const [saved,setSaved]=useState<string[]>(()=>read('saved',[]));const [applied,setApplied]=useState<string[]>(()=>read('applied',[]));
 const [tab,setTab]=useState<'overview'|'company'>('overview');const [jdTab,setJdTab]=useState<'jd'|'skills'>('jd');const [sort,setSort]=useState('default');const [mobileDetail,setMobileDetail]=useState(false);
 const [profile,setProfile]=useState<Profile>(()=>read('profile',{text:'',education:''}));const [draft,setDraft]=useState(profile);const [toast,setToast]=useState('');const [dialogKind,setDialogKind]=useState<'profile'|'help'>('profile');const dialog=useRef<HTMLDialogElement>(null);const detail=useRef<HTMLDivElement>(null);
 const filtered=useMemo(()=>{
  const tokens=query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  const list=source.filter(j=>(!company||j.company_name===company)&&(!recruitmentType||j.recruitment_type===recruitmentType)&&(!city||j.locations.includes(city))&&(!direction||j.job_direction===direction)&&(!degree||j.education_requirement===degree)&&(view!=='saved'||saved.includes(j.source_job_id))&&(view!=='applied'||applied.includes(j.source_job_id))&&tokens.every(q=>[j.job_title,j.company_name,j.job_subdirection,...j.skills].join(' ').toLowerCase().includes(q)));
  if(sort==='published')return [...list].sort((a,b)=>{const ad=a.published_at?publishedDate(a.published_at):'';const bd=b.published_at?publishedDate(b.published_at):'';return bd.localeCompare(ad);});
  return sort==='name'?[...list].sort((a,b)=>shortTitle(a.job_title).localeCompare(shortTitle(b.job_title),'zh-CN')):list;
 },[query,city,direction,degree,company,recruitmentType,view,saved,applied,sort]);
 const job=filtered.find(j=>j.source_job_id===selectedId)||filtered[0];
 useEffect(()=>{if(job&&job.source_job_id!==selectedId)setSelectedId(job.source_job_id);},[job,selectedId]);
 useEffect(()=>{const p=new URLSearchParams();if(company)p.set('company',company);if(recruitmentType)p.set('type',recruitmentType);if(query)p.set('q',query);if(city)p.set('city',city);if(direction)p.set('direction',direction);if(degree)p.set('degree',degree);if(selectedId)p.set('job',selectedId);history.replaceState(null,'',`${location.pathname}?${p}`);},[query,city,direction,degree,company,recruitmentType,selectedId]);
 useEffect(()=>{try{localStorage.setItem('jobkoi-preview:saved',JSON.stringify(saved));localStorage.setItem('jobkoi-preview:applied',JSON.stringify(applied));localStorage.setItem('jobkoi-preview:profile',JSON.stringify(profile));}catch{setToast('浏览器未允许保存，本次操作仍然有效');}},[saved,applied,profile]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),3000);return()=>clearTimeout(id);},[toast]);
 const toggleSave=(id:string)=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const selectJob=(j:Job)=>{setSelectedId(j.source_job_id);setTab('overview');setMobileDetail(true);detail.current?.scrollTo({top:0});};
 const openDialog=(kind:'profile'|'help')=>{setDialogKind(kind);setDraft(profile);dialog.current?.showModal();};
 const reset=()=>{setQuery('');setCity('');setDirection('');setDegree('');setCompany('');setRecruitmentType('');};
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)&&!dialog.current?.open){e.preventDefault();document.querySelector<HTMLInputElement>('.search-box input')?.focus();}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[]);
 const match=job?.skills.filter((s: string)=>profile.text.toLowerCase().includes(s.toLowerCase()))||[];
 const hasFilters=!!(query||city||direction||degree||company||recruitmentType);
 const setActiveView=(v:'all'|'saved'|'applied')=>{setView(v);setMobileDetail(false);};
 return <div className="discovery-app">
  <header className="topbar">
   <a className="brand" href="/job-discovery.html" aria-label="JobKoI 岗位首页"><span className="brand-mark"><Layers size={23}/></span>JobKoI<span className="brand-cn">求职方舟</span></a>
   <nav aria-label="主导航"><button className={view==='all'?'nav-active':''} onClick={()=>setActiveView('all')}>发现岗位</button><button className={view==='saved'?'nav-active':''} onClick={()=>setActiveView('saved')}>我的收藏{saved.length>0&&<span className="nav-count">{saved.length}</span>}</button><button className={view==='applied'?'nav-active':''} onClick={()=>setActiveView('applied')}>投递记录{applied.length>0&&<span className="nav-count">{applied.length}</span>}</button><button onClick={()=>openDialog('profile')}>求职档案</button></nav>
   <div className="topbar-right"><span className="preview-label">本地预览</span><button className="icon-button help-button" aria-label="使用说明" onClick={()=>openDialog('help')}><CircleHelp size={19}/></button><button className="avatar" aria-label="编辑求职档案" onClick={()=>openDialog('profile')}><UserRound size={19}/></button></div>
  </header>
  <main className="workspace">
   <section className="filterbar" aria-label="岗位搜索与筛选">
    <label className="search-box"><Search size={20}/><input aria-label="搜索岗位" value={query} onChange={e=>setQuery(e.target.value)} placeholder="寻找你的下一站 · 搜岗位、技能或公司"/>{query&&<button aria-label="清空搜索" className="icon-button" onClick={()=>setQuery('')}><X size={16}/></button>}<kbd>/</kbd></label>
    <div className="filters"><label className={city?'filter chosen':'filter'}><MapPin size={15}/><select aria-label="工作地点" value={city} onChange={e=>setCity(e.target.value)}><option value="">工作地点</option>{cities.map(c=><option key={c}>{c}</option>)}</select><ChevronDown size={14}/></label><label className={company?'filter chosen':'filter'}><Building2 size={15}/><select aria-label="公司" value={company} onChange={e=>setCompany(e.target.value)}><option value="">全部公司</option>{companies.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label><label className={recruitmentType?'filter chosen':'filter'}><select aria-label="招聘类型" value={recruitmentType} onChange={e=>setRecruitmentType(e.target.value)}><option value="">招聘类型</option>{recruitmentTypes.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label><label className={direction?'filter chosen':'filter'}><select aria-label="岗位方向" value={direction} onChange={e=>setDirection(e.target.value)}><option value="">岗位方向</option>{directions.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label><label className={degree?'filter chosen':'filter'}><SlidersHorizontal size={15}/><select aria-label="学历要求" value={degree} onChange={e=>setDegree(e.target.value)}><option value="">学历要求</option>{degrees.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label>{hasFilters&&<button className="reset-filter" onClick={reset} title="重置筛选" aria-label="重置筛选"><RotateCcw size={17}/></button>}</div>
   </section>
   <div className={`job-workspace ${mobileDetail?'show-detail':''}`}>
    <aside className="job-list-panel" aria-label="岗位列表">
     <div className="list-toolbar"><div><strong>{filtered.length}</strong> 个{view==='saved'?'收藏':view==='applied'?'已投递':''}岗位</div><label className="sort"><select aria-label="排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="default">默认排序</option><option value="name">岗位名称</option><option value="published">最新发布</option></select><ChevronDown size={13}/></label></div>
     <div className="list-scroll">{filtered.length===0?<div className="empty"><Search size={30}/><h3>{view==='saved'?'还没有收藏的岗位':view==='applied'?'还没有投递记录':'没有找到相关岗位'}</h3><p>{hasFilters?'试试减少筛选条件，或换个关键词。':'从岗位右上角收藏或标记已投递。'}</p>{hasFilters&&<button className="secondary" onClick={reset}>清除筛选</button>}</div>:filtered.map(j=><article className={`job-card ${job?.source_job_id===j.source_job_id?'selected':''}`} key={j.source_job_id}>
      <button className="job-card-main" aria-pressed={job?.source_job_id===j.source_job_id} onClick={()=>selectJob(j)}><CompanyLogo job={j}/><span className="card-copy"><h2>{shortTitle(j.job_title)}</h2><span className="card-company">{j.company_name}<span className="company-verified"><Check size={9}/></span></span><span className="card-location">{j.locations.join(' / ')}</span><span className="card-meta">{j.education_requirement||'学历未注明'}<i/> {j.job_subdirection}</span><span className="card-bottom"><span className="card-type">{j.recruitment_type}</span><span className="card-direction">{j.job_direction}</span><span>{applied.includes(j.source_job_id)?'已标记投递':null}</span></span><span className="card-published">发布时间：{publishedDate(j.published_at)}</span></span></button>
      <button aria-label={`${saved.includes(j.source_job_id)?'取消收藏':'收藏'} ${shortTitle(j.job_title)}`} className={`save-card ${saved.includes(j.source_job_id)?'is-saved':''}`} onClick={()=>toggleSave(j.source_job_id)}><Bookmark size={17} fill={saved.includes(j.source_job_id)?'currentColor':'none'}/></button>
     </article>)}</div><footer className="list-footer"><ShieldCheck size={13}/>官网岗位 · 采集于 2026 年 9 月 13–15 日</footer>
    </aside>
    <section className="detail-panel" aria-label="岗位详情">
     {!job?<div className="empty detail-empty"><BriefcaseBusiness size={36}/><h2>好机会，值得慢慢找</h2><p>调整筛选条件后，在左侧选择一个岗位。</p></div>:<>
      <div className="detail-toolbar"><button className="mobile-back icon-button" aria-label="返回岗位列表" onClick={()=>setMobileDetail(false)}><ArrowLeft size={20}/></button><div className="detail-tabs" role="tablist" aria-label="详情类型"><button role="tab" aria-selected={tab==='overview'} className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>岗位概览</button><button role="tab" aria-selected={tab==='company'} className={tab==='company'?'active':''} onClick={()=>setTab('company')}>公司与招聘</button></div><div className="detail-actions"><button className={`applied-button ${applied.includes(job.source_job_id)?'marked':''}`} onClick={()=>{setApplied(a=>a.includes(job.source_job_id)?a.filter(x=>x!==job.source_job_id):[...a,job.source_job_id]);setToast(applied.includes(job.source_job_id)?'已移除投递标记':'已记入本地投递记录');}}>{applied.includes(job.source_job_id)?<CheckCheck size={15}/>:null}{applied.includes(job.source_job_id)?'已投递':'标记已投递'}</button><button className={`secondary save-detail ${saved.includes(job.source_job_id)?'is-saved':''}`} onClick={()=>toggleSave(job.source_job_id)}><Bookmark size={16} fill={saved.includes(job.source_job_id)?'currentColor':'none'}/>{saved.includes(job.source_job_id)?'已收藏':'收藏'}</button><a className="primary" target="_blank" rel="noreferrer" href={job.application_url}>官网投递<ArrowUpRight size={16}/></a></div></div>
      <div className="detail-scroll" ref={detail} key={`${job.source_job_id}-${tab}`}>
       {tab==='company'?<div className="company-page"><div className="company-hero"><CompanyLogo job={job} large/><div><span className="eyebrow">官方招聘</span><h1>{job.company_name}</h1><p>{[...new Set(source.filter(j=>j.company_name===job.company_name).map(j=>j.recruitment_type))].join('、')}招聘</p></div></div><h2>从感兴趣的方向出发</h2><div className="company-directions">{[...new Set(source.filter(j=>j.company_name===job.company_name).map(j=>j.job_direction))].map(dir=><button key={dir} onClick={()=>{reset();setCompany(job.company_name);setDirection(dir);setTab('overview');setView('all')}}><span>{dir}</span><strong>{source.filter(j=>j.company_name===job.company_name&&j.job_direction===dir).length}<small> 个岗位</small></strong><ArrowUpRight size={18}/></button>)}</div><section className="company-rules"><h2>投递前，先确认这些规则</h2><p>当前收录{[...new Set(source.filter(j=>j.company_name===job.company_name).map(j=>j.recruitment_type))].join('、')}岗位。具体资格、投递规则及最新状态，请以官网为准。</p><a href={job.source_list_url} target="_blank" rel="noreferrer" className="text-link">查看{job.company_name}招聘官网 <ExternalLink size={14}/></a></section></div>:<div className="detail-columns">
        <div className="job-facts"><div className="facts-top"><span className="status-pill">{job.recruitment_type}</span><button className="icon-button" aria-label="复制岗位链接" onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setToast('已复制本地岗位链接')}catch{setToast('复制失败，请复制浏览器地址栏链接')}}}><Copy size={16}/></button></div><h1>{shortTitle(job.job_title)}</h1><p className="verified-line"><ShieldCheck size={14}/>官网已核验 · {job.verified_date.replaceAll('-','.')}</p><div className="company-identity"><CompanyLogo job={job} large/><div><h2>{job.company_name} <CheckCircle2 size={14}/></h2><button className="text-link" onClick={()=>setTab('company')}>查看公司与招聘 <ChevronRight size={13}/></button></div></div><div className="facts-group"><div className="fact"><MapPin size={17}/><div><span>工作地点</span><strong>{job.locations.join(' / ')||'官网未注明'}</strong></div></div><div className="fact"><GraduationCap size={17}/><div><span>学历要求</span><strong>{job.education_requirement||'官网未注明'}</strong></div></div><div className="fact"><Layers size={17}/><div><span>岗位方向</span><strong>{job.job_direction||'官网未注明'}</strong></div></div><div className="fact"><Clock3 size={17}/><div><span>发布时间</span><strong>{publishedDate(job.published_at)}</strong></div></div></div></div>
        <div className="job-content"><div className="content-switch" role="tablist"><button className={jdTab==='jd'?'on':''} onClick={()=>setJdTab('jd')}>完整岗位 JD</button><button className={jdTab==='skills'?'on':''} onClick={()=>setJdTab('skills')}>我的匹配线索</button></div>{jdTab==='jd'?<><div className="section-heading"><h2>岗位 JD</h2><span>官网完整描述</span></div><div className="jd"><p>{job.jd||'官网未披露岗位描述。'}</p></div></>:<div className="match-section"><h2>我的匹配线索</h2>{match.length?<div className="match-tags">{match.map((s:string)=><span key={s}><Check size={13}/>{s}</span>)}</div>:<div className="match-empty"><Sparkles size={26}/><h3>添加求职档案后查看匹配</h3><p>在档案中填写技能和项目经历，系统会从岗位要求中标出关键词。</p></div>}</div>}<div className="jd-footer"><span>最近核验：{job.verified_date}</span><a href={job.detail_url} target="_blank" rel="noreferrer">以官网最新信息为准 <ExternalLink size={13}/></a></div></div>
       </div>}
      </div>
     </>}
    </section>
   </div>
  </main>
  {toast&&<div className="toast" role="status"><CheckCircle2 size={17}/>{toast}</div>}
  <dialog ref={dialog} className="profile-dialog"><div className="dialog-header"><h2>{dialogKind==='profile'?'你的求职档案':'关于这个本地预览'}</h2><button className="icon-button" aria-label="关闭弹窗" onClick={()=>dialog.current?.close()}><X size={20}/></button></div>{dialogKind==='help'?<div className="help-content"><p>{source.length} 个岗位来自招聘官网：{companies.map(name=>`${name} ${companyCount(name)} 个`).join("，")}。采集于 2026 年 9 月 13–15 日。招聘类型按官网信息标注；发布时间未公布的岗位不会使用采集日期替代。</p><p>可以搜索、筛选、收藏和标记投递。收藏、档案与投递标记仅保存在当前浏览器，不会提交到招聘网站。</p><p>“官网投递”会打开招聘官网。只有手动标记，岗位才会进入投递记录。</p><button className="primary" onClick={()=>dialog.current?.close()}>知道了</button></div>:<form onSubmit={e=>{e.preventDefault();setProfile(draft);dialog.current?.close();setToast('求职档案已保存在当前浏览器');}}><p className="muted">用技能和经历找到匹配线索。此预览不会上传你的资料。</p><label>学历<select aria-label="学历" value={draft.education} onChange={e=>setDraft({...draft,education:e.target.value})}><option value="">请选择学历</option>{['大专','本科','硕士','博士'].map(x=><option key={x}>{x}</option>)}</select></label><label>技能与项目经历<textarea required rows={8} value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})} placeholder="例如：熟悉 React、TypeScript，使用 Python 搭建过一个数据分析项目……"/></label><div className="dialog-footer"><button type="button" className="secondary" onClick={()=>dialog.current?.close()}>取消</button><button type="submit" className="primary">保存档案</button></div></form>}</dialog>
 </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);


